version: "3.8"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kaspersky-checker-api
    env_file:
      - .env
    ports:
      # FastAPI HTTP API доступен извне
      - "8000:8000"
    volumes:
      # Монтируем каталог проекта внутрь контейнера для разработки
      - ./:/app:delegated
    restart: unless-stopped
    environment:
      # Передваем переменные окружения в контейнер
      - API_KEY=${API_KEY}
      - KASP_ADB_HOST=${KASP_ADB_HOST}
      - KASP_ADB_PORT=${KASP_ADB_PORT}
      - TC_ADB_HOST=${TC_ADB_HOST}
      - TC_ADB_PORT=${TC_ADB_PORT}

# Файл .env рядом с этим compose:
# API_KEY=your-super-secret-key
# ADB_HOST=127.0.0.1
# ADB_PORT=5555
