version: "3.8"

networks:
  caddy:
    external: true

services:
  api:
    networks: [caddy]
    expose: ["8000"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-checker-api
    env_file:
      - .env
    volumes:
      # Mount project directory inside container for development
      - ./:/app:delegated
    restart: unless-stopped
    environment:
      # Pass environment variables to the container
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - KASP_ADB_HOST=${KASP_ADB_HOST}
      - KASP_ADB_PORT=${KASP_ADB_PORT}
      - TC_ADB_HOST=${TC_ADB_HOST}
      - TC_ADB_PORT=${TC_ADB_PORT}
      - GC_ADB_HOST=${GC_ADB_HOST}
      - GC_ADB_PORT=${GC_ADB_PORT}
      - PG_HOST=${PG_HOST}
      - PG_PORT=${PG_PORT}
      - PG_DB=${PG_DB}
      - PG_USER=${PG_USER}
      - PG_PASSWORD=${PG_PASSWORD}
      - USE_REDIS=1
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - db
      - redis
    labels:
      caddy: telephony.visotsky.com
      caddy.reverse_proxy: "{{upstreams 8000}}"

  db:
    image: postgres:16
    container_name: phone-checker-db
    networks: [caddy]
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7
    container_name: phone-checker-redis
    networks: [caddy]
    restart: unless-stopped
    volumes:
      - redisdata:/data
    ports:
      - "6379:6379"

volumes:
  pgdata:
  redisdata:

# .env file next to this compose:
# API_KEY=your-super-secret-key
# ADB_HOST=127.0.0.1
# ADB_PORT=5555