version: "3.8"

networks:
  caddy:
    external: true

services:
  api:
    networks: [caddy]
    expose: ["8000"]
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-checker-api
    env_file:
      - .env
    volumes:
      # Mount project directory inside container for development
      - ./:/app:delegated
    restart: unless-stopped
    environment:
      # Pass environment variables to the container
      - API_KEY=${API_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - KASP_ADB_HOST=${KASP_ADB_HOST}
      - KASP_ADB_PORT=${KASP_ADB_PORT}
      - TC_ADB_HOST=${TC_ADB_HOST}
      - TC_ADB_PORT=${TC_ADB_PORT}
      - GC_ADB_HOST=${GC_ADB_HOST}
      - GC_ADB_PORT=${GC_ADB_PORT}
    labels:
      caddy: telephony.visotsky.com
      caddy.reverse_proxy: "{{upstreams 8000}}"

# .env file next to this compose:
# API_KEY=your-super-secret-key
# ADB_HOST=127.0.0.1
# ADB_PORT=5555