version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: phone-spam-checker
    restart: unless-stopped
    ports:
      - "8000:8000"  # API
      - "8001:8001"  # Prometheus metrics
    environment:
      - REDIS_URL=redis://redis:6379/0
      - API_KEY=${API_KEY:-changeme}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
      - CACHE_ENABLED=${CACHE_ENABLED:-true}
      - CACHE_TTL=${CACHE_TTL:-86400}
      - METRICS_PORT=8001
      - KASP_ADB_HOST=${KASP_ADB_HOST:-127.0.0.1}
      - KASP_ADB_PORT=${KASP_ADB_PORT:-5555}
      - TC_ADB_HOST=${TC_ADB_HOST:-127.0.0.1}
      - TC_ADB_PORT=${TC_ADB_PORT:-5556}
      - GC_ADB_HOST=${GC_ADB_HOST:-127.0.0.1}
      - GC_ADB_PORT=${GC_ADB_PORT:-5557}
    volumes:
      - ./logs:/app/logs
    depends_on:
      - redis
    networks:
      - phone-checker-network

  redis:
    image: redis:6-alpine
    container_name: phone-checker-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    networks:
      - phone-checker-network

networks:
  phone-checker-network:
    driver: bridge

volumes:
  redis-data:
